INSERT INTO sport (id, name, slug, in_home, duration) VALUES (1,'FOOTBALL','football',1,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (2,'BASKETBALL','basketball',1,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (3,'TENNIS','tennis',1,240);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (4,'ICE HOCKEY','ice-hockey',1,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (5,'RUGBY','rugby',1,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (6,'AM. FOOTBALL','am-football',1,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (7,'CONTACT','contact',1,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (8,'MOTOSPORT','motosport',1,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (9,'GOLF','golf',0,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (10,'DARTS','darts',0,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (11,'POKER','poker',0,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (12,'SNOOKER','snooker',0,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (13,'HANDBALL','handball',0,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (14,'VOLLEYBALL','volleyball',0,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (15,'TV','tv',0,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (16,'OTHERS','others',0,120);



INSERT INTO league (id, id_sport, name, show_icon) VALUES (1,1,'Alemania - German Bundesliga DFB Pokal ',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (2,1,'Argentina - Primera Division Copa Argentina',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (3,1,'Australia - Australian A-League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (4,1,'Austria - Austrian Bundesliga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (5,1,'Azerbaijan - Azerbaijan Premier League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (6,1,'Belgica - Belgian Pro League Belgium',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (7,1,'Brasil - Brasileirao Serie A Serie B',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (8,1,'Bulgaria - Bulgarian A Football Group',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (9,1,'Canadian Football League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (10,1,'Chile - Chilean Primera División',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (11,1,'China - Chinese Super League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (12,1,'Colombia - Colombian League Categoría Primera A',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (13,1,'Corea del Sur - South Korea\'s K-League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (14,1,'Croacia - Croatian League HNL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (15,1,'Dinamarca - Danish Super League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (16,1,'Ecuador - Ecuador Serie A ',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (17,1,'Egypto - Egyptian Premier League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (18,1,'Emiratos Arabes Unidos - UAE League Emirates',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (19,1,'Escocia - PremierShip Scotland',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (20,1,'Eslovaquia - Slovak Super League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (21,1,'Eslovenia - Slovenian PrvaLiga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (22,1,'España - Spanish Primera Division Copa del Rey',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (23,1,'Finlandia - Finnish league Veikkausliiga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (24,1,'Francia - French Ligue 1 Ligue 2 Coupe de la Ligue',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (25,1,'Grecia - Greek Super League Greece',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (26,1,'Holanda - Dutch League Eredivisie',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (27,1,'Hungria - Hungarian League Nemzeti Bajnokság',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (28,1,'India - I-League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (29,1,'Inglaterra - English Premier League FA Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (30,1,'Islandia - Football Association of Iceland',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (31,1,'Israel - Israeli Premier League Ligat ha\'Al',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (32,1,'Italia - Italian Serie A Serie B',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (33,1,'Japon - Japanese J-League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (34,1,'Lituania - Lithuanian A Lyga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (35,1,'Marruecos - Morocco League Botola',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (36,1,'Mexico - Mexican League MX',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (37,1,'Noruega - Norwegian Tippeligaen',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (38,1,'Paraguay - Paraguay Primera División',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (39,1,'Perú - Peruvian Primera División',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (40,1,'Polonia - Premier League Poland Ekstraklasa',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (41,1,'Portugal - Portuguese Liga Sagres',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (42,1,'Republica Checa - Czech Liga League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (43,1,'Rumania - Soccer Romania Liga I',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (44,1,'Rusia - Russian Premier League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (45,1,'Serbia - Serbian SuperLiga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (46,1,'Suecia - Swedish League Allsvenskan',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (47,1,'Suiza - Swiss Super League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (48,1,'Turquia - Turkish SuperLiga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (49,1,'Ucrania - Ukrainian Premier League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (50,1,'Uruguay - Uruguayan Primera División',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (51,1,'USA - USA Major League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (52,1,'UEFA Champions League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (53,1,'UEFA Europa League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (54,1,'Eurocopa',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (55,1,'UEFA Super Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (56,1,'Derby Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (57,1,'Emirates Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (58,1,'Copa del Mundo',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (59,1,'Audi Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (60,1,'Mundial Clubes FIFA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (61,1,'CONCACAF Liga de Campeones',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (62,1,'Copa Libertadores',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (63,1,'Copa Sudamericana',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (64,1,'Campeonato Africano de Naciones',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (65,1,'FIFA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (66,1,'FOOTBALL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (67,2,'NBA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (68,2,'NCAA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (69,2,'Euroliga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (70,2,'Eurocup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (71,2,'WNBA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (72,2,'Liga Sudamericana de Basquet',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (73,2,'FIBA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (74,2,'BASKETBALL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (75,3,'TENNIS',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (76,4,'NHL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (77,4,'ICE HOCKEY',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (78,5,'Rugby Top 14',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (79,5,'Super League Rugby',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (80,5,'NRL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (81,5,'Sevens World Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (82,5,'Super Rugby',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (83,5,'RUGBY',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (84,6,'NFL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (85,6,'NCAAF',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (86,6,'CFL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (87,6,'AMERICAN FOOTBALL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (88,7,'BOX',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (89,7,'UFC',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (90,7,'WWE',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (91,7,'TNA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (92,8,'Formula 1',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (93,8,'NASCAR',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (94,8,'MOTORSPORTS',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (95,9,'GOLF',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (96,10,'DARTS',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (97,11,'POKER',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (98,12,'SNOOKER',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (99,13,'HANDBALL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (100,14,'VOLLEYBALL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (101,15,'ESPN',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (102,15,'TV',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (103,16,'ATLETISMO',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (104,16,'CICLISMO',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (105,16,'PING PONG',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (106,16,'HORSE RACING',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (107,16,'BADMINTON',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (108,16,'NATACIÓN',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (109,16,'OLYMPIC GAMES RIO 2016',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (110,16,'OTHERS',1);