-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (1,'FUTBOL','futbol',1,90);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (2,'TENNIS','tennis',1,120);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (3,'BASQUET','basquet',1,120);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (4,'RUGBY','rugby',1,120);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (5,'HOCKEY','hockey',1,120);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (6,'FOOTBALL AMERICANO','football-americano',0,120);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (7,'BOXEO','boxeo',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (8,'UFC','ufc',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (9,'WWE','wwe',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (10,'TNA','tna',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (11,'MOTOSPORT','motosport',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (12,'SERIES DE TV','series-de-tv',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (13,'CICLISMO','ciclismo',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (14,'ATLETISMO','atletismo',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (15,'SNOOKER','snooker',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (16,'POKER','poker',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (17,'DARTS','darts',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (18,'HANDBALL','handball',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (19,'GOLF','golf',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (20,'VOLLEY','volley',0,60);
-- INSERT INTO sport (id, name, slug, in_home, duration) VALUES (21,'CANALES TV','canales-tv',0,60);
-- 
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (1,1,'German Bundesliga',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (2,1,'German 2. Bundesliga',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (3,1,'German 3. Bundesliga',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (4,1,'DFB Pokal',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (5,1,'Primera Division',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (6,1,'Torneo Argentina A',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (7,1,'Copa Argentina',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (8,1,'Australia A-League',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (9,1,'Austria - Bundesliga',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (10,1,'Belgica Jupiler League',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (11,1,'Brasileirao Serie A',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (12,1,'Brasileirao Serie B',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (13,1,'Campeonato Paulista',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (14,1,'Primera Division',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (15,1,'China-Superliga',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (16,1,'Primera Division',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (17,1,'Serie A',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (18,1,'UAE League',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (19,1,'PremierShip',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (20,1,'Spanish Primera Division',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (21,1,'Copa del Rey',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (22,1,'Supercopa',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (23,1,'Spanish Liga Adelante',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (24,1,'French Ligue 1',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (25,1,'French Ligue 2',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (26,1,'Greece Super League',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (27,1,'English Premier League',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (28,1,'English Npower Championship',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (29,1,'FA Cup',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (30,1,'Italia Serie A',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (31,1,'Italia Serie B',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (32,1,'Japanese J-League',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (33,1,'Mexican League MX',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (34,1,'Norwegian Elitserien',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (35,1,'Portuguese Liga Sagres',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (36,1,'Primera Division',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (37,1,'Turkish Superliga',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (38,1,'Primera Division',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (39,1,'USA Major League',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (40,1,'UEFA Champions League',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (41,1,'UEFA Europa League',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (42,1,'Eurocopa',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (43,1,'UEFA Super Cup',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (44,1,'Derby Cup',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (45,1,'Emirates Cup',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (46,1,'Copa del Mundo',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (47,1,'Audi Cup',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (48,1,'Mundial Clubes FIFA',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (49,1,'Copa Cofederanciones FIFA',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (50,1,'CONCACAF Liga de Campeones',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (51,1,'Copa Libertadores',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (52,1,'Copa Sudamericana',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (53,1,'Campeonato Sudamericano sub-20',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (54,1,'Campeonato Africano de Naciones',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (55,2,'Abierto de Australia',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (56,2,'Torneo de Roland Garros',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (57,2,'Campeonato de Wimbledon',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (58,2,'Abierto de Estados Unidos',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (59,2,'Masters de Indian Wells Estados Unidos',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (60,2,'Masters de Miami Estados Unidos ',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (61,2,'Masters de Monte Carlo Mónaco',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (62,2,'Masters de Roma Italia ',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (63,2,'Masters de Madrid España ',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (64,2,'Masters de Canadá - Rogers Cup Canadá ',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (65,2,'Masters de Cincinnati Estados Unidos ',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (66,2,'Masters de Shanghai China ',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (67,2,'Masters de París Francia',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (68,3,'BBL',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (69,3,'A1',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (70,3,'TBL',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (71,3,'NBA',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (72,3,'NCAA',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (73,3,'Euroliga',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (74,3,'Eurocup',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (75,4,' Rugby Top 14',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (76,4,'Super League Rugby',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (77,4,'NRL',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (78,4,'Sevens Worl Cup',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (79,4,'Super Rugby',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (80,5,'NHL',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (81,6,'NFL',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (82,6,'NCAAF',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (83,6,'CFL',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (84,7,'BOX',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (85,8,'UFC',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (86,9,'WWE',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (87,10,'TNA',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (88,11,'Formula 1',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (89,11,'NASCAR',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (90,12,'TV Series',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (91,13,'CICLISMO',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (92,14,'ATLETISMO',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (93,15,'SNOOKER',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (94,16,'POKER',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (95,17,'DARTS',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (96,18,'HANDBALL',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (97,19,'GOLF',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (98,20,'VOLLEY',0);
-- INSERT INTO league (id, id_sport, name, show_icon) VALUES (99,21,'CANALES TV',0);


INSERT INTO sport (id, name, slug, in_home, duration) VALUES (1,'FOOTBALL','football',1,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (2,'BASKETBALL','basketball',1,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (3,'TENNIS','tennis',1,240);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (4,'ICE HOCKEY','ice-hockey',1,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (5,'RUGBY','rugby',1,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (6,'AM. FOOTBALL','am.-football',1,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (7,'CONTACT','contact',1,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (8,'MOTOSPORT','motosport',1,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (9,'GOLF','golf',0,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (10,'DARTS','darts',0,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (11,'POKER','poker',0,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (12,'SNOOKER','snooker',0,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (13,'HANDBALL','handball',0,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (14,'VOLLEYBALL','volleyball',0,120);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (15,'TV','tv',0,60);
INSERT INTO sport (id, name, slug, in_home, duration) VALUES (16,'OTHERS','others',0,60);

INSERT INTO league (id, id_sport, name, show_icon) VALUES (1,1,'Alemania - German Bundesliga DFB Pokal ',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (2,1,'Argentina - Primera Division Copa Argentina',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (3,1,'Australia - Australian A-League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (4,1,'Austria - Austrian Bundesliga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (5,1,'Azerbaijan - Azerbaijan Premier League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (6,1,'Belgica - Belgian Pro League Belgium',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (7,1,'Brasil - Brasileirao Serie A Serie B',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (8,1,'Bulgaria - Bulgarian A Football Group',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (9,1,'Chile - Chilean Primera División',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (10,1,'China - Chinese Super League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (11,1,'Colombia - Colombian League Categoría Primera A',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (12,1,'Corea del Sur - South Korea's K-League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (13,1,'Croacia - Croatian League HNL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (14,1,'Dinamarca - Danish Super League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (15,1,'Ecuador - Ecuador Serie A',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (16,1,'Egypto - Egyptian Premier League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (17,1,'Emiratos Arabes Unidos - UAE League Emirates',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (18,1,'Escocia - PremierShip Scotland',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (19,1,'Eslovaquia - Slovak Super League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (20,1,'Eslovenia - Slovenian PrvaLiga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (21,1,'España - Spanish Primera Division Copa del Rey',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (22,1,'Finlandia - Finnish league Veikkausliiga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (23,1,'Francia - French Ligue 1 Ligue 2 Coupe de la Ligue',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (24,1,'Grecia - Greek Super League Greece',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (25,1,'Hungria - Hungarian League Nemzeti Bajnokság',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (26,1,'Inglaterra - English Premier League FA Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (27,1,'Islandia - Football Association of Iceland',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (28,1,'Israel - Israeli Premier League Ligat ha'Al',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (29,1,'Italia - Italian Serie A Serie B',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (30,1,'Japon - Japanese J-League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (31,1,'Lituania - Lithuanian A Lyga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (32,1,'Marruecos - Morocco League Botola',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (33,1,'Mexico - Mexican League MX',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (34,1,'Noruega - Norwegian Tippeligaen',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (35,1,'Perú - Peruvian Primera División',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (36,1,'Polonia - Premier League Poland Ekstraklasa',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (37,1,'Portugal - Portuguese Liga Sagres',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (38,1,'Republica Checa - Czech Liga League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (39,1,'Rumania - Soccer Romania Liga I',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (40,1,'Serbia - Serbian SuperLiga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (41,1,'Suecia - Swedish League Allsvenskan',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (42,1,'Suiza - Swiss Super League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (43,1,'Turquia - Turkish SuperLiga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (44,1,'Ucrania - Ukrainian Premier League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (45,1,'Uruguay - Uruguayan Primera División',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (46,1,'USA - USA Major League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (47,1,'UEFA Champions League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (48,1,'UEFA Europa League',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (49,1,'Eurocopa',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (50,1,'UEFA Super Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (51,1,'Derby Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (52,1,'Emirates Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (53,1,'Copa del Mundo',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (54,1,'Audi Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (55,1,'Mundial Clubes FIFA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (56,1,'CONCACAF Liga de Campeones',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (57,1,'Copa Libertadores',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (58,1,'Copa Sudamericana',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (59,1,'Campeonato Africano de Naciones',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (60,1,'FIFA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (61,1,'FOOTBALL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (62,2,'NBA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (63,2,'NCAA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (64,2,'Euroliga',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (65,2,'Eurocup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (66,2,'WNBA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (67,2,'Liga Sudamericana de Basquet',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (68,2,'FIBA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (69,2,'BASKETBALL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (70,3,'TENNIS',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (71,4,'NHL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (72,4,'ICE HOCKEY',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (73,5,'Rugby Top 14',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (74,5,'Super League Rugby',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (75,5,'NRL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (76,5,'Sevens World Cup',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (77,5,'Super Rugby',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (78,5,'RUGBY',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (79,6,'NFL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (80,6,'NCAAF',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (81,6,'CFL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (82,6,'AMERICAN FOOTBALL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (83,7,'BOX',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (84,7,'UFC',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (85,7,'WWE',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (86,7,'TNA',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (87,8,'Formula 1',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (88,8,'NASCAR',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (89,8,'MOTORSPORTS',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (90,9,'GOLF',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (91,10,'DARTS',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (92,11,'POKER',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (93,12,'SNOOKER',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (94,13,'HANDBALL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (95,14,'VOLLEYBALL',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (96,15,'ESPN',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (97,15,'TV',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (98,16,'ATLETISMO',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (99,16,'CICLISMO',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (100,16,'PING PONG',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (101,16,'HORSE RACING',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (102,16,'BADMINTON',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (103,16,'NATACIÓN',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (104,16,'OLYMPIC GAMES RIO 2016',1);
INSERT INTO league (id, id_sport, name, show_icon) VALUES (105,16,'OTHERS',1);