<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="<?=$this->url(array(),'admin')?>"><?=$this->appTitle?></a>
            <div class="nav-collapse collapse">
                <p class="navbar-text pull-right">
                    Logged in as <a href="<?=$this->url(array(),'admin')?>" class="navbar-link"><?=$this->authData['user']?></a>
                </p>
                <ul class="nav">
                    <li class="active"><a href="<?=$this->url(array(),'admin')?>">Home</a></li>
                    <li><a href="<?=$this->url(array(),'logout',true)?>">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
