<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">

        <?= $this->headTitle() ?>

        <?= $this->headMeta() ?>

        <?= $this->headLink() ?>

        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="../assets/ico/favicon.png">
    </head>
    <body>
        <?= $this->render('_navbar.phtml') ?>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span2"><?= $this->render('_sidebar.phtml') ?></div>
                <div class="span10"><?= $this->layout()->content ?></div>
            </div>
            <?= $this->render('_footer.phtml') ?>
        </div>
        <?= $this->headScript() ?>
    </body>    
</html>
