<div class="masthead">
    <div class="navbar" id="navbar-sports">
        <div class="navbar-inner">
            <div class="container">
                <ul class="nav">
                    <? foreach ($this->sports as $sport): ?>
                        <li<?=($this->selectedSport == $sport->slug) ? ' class="active"' : '' ?>><a href="<?= $this->url(array('sport' => $sport->slug), 'home-sport', true) ?>"><?= $sport->name ?></a></li>
                    <? endforeach; ?>
                    <li<?=($this->selectedSport == 'others') ? ' class="active"' : '' ?>><a href="<?= $this->url(array('sport' => 'others'), 'home-sport', true) ?>">Others</a></li>          
                </ul>
            </div>
        </div>
    </div>
</div>
