<?= $this->render('index/_masthead.phtml') ?>



<? foreach ($this->eventsByDate as $date => $events):  ?>

    <h3 class="muted">Events for <?=($date==date('Y-m-d'))?'Today':$date?></h3>

    <table id="tbl-reporte-ventas" class="table table-striped table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($events as $item): /*$item = (array) $item;*/ ?>
                <tr>
                    <td>
                        <span class="trigger_event" data-ide="<?= $item['ide'] ?>" data-url="<?=$this->url(array('module'=>'default','controller'=>'index','ide'=>'__IDE__','action'=>'get-options'),'default',true)?>">
                            <img width="25" src="/static/img/icons/<?=($item['show_icon'])?('league/'.$item['idl']):('sport/'.$item['ids'])?>.png" />
                            <? $d = new DateTime($item['dt']); echo $d->format('H:i'); ?>
                            <?= $item['event'] ?>
                        </span>
                    </td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>
    
<? endforeach; ?>
