<?= $this->render('index/_masthead.phtml') ?>

<h3 class="muted">Events for Today</h3>


<table id="tbl-reporte-ventas" class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>Id</th>
            <th>Status</th>
            <th>Company</th>
            <th>Payment</th>
            <th>Price</th>
            <th>When?</th>
            <th>Route</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>10211</td>
            <td><span class="label label-success">pagado</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-important">pen</span>
                140.00                                            </td>
            <td>
                PEN                        140.00                    </td>
            <td>
                2013-06-19                        11:22:16                    </td>
            <td>
                Cusco -
                Lima                    </td>
            <td>
                2 Passengers 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10211" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10212</td>
            <td><span class="label label-warning">pendiente</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-info">usd</span>
                30.60                                                    (2.619)
            </td>
            <td>
                PEN                        80.00                    </td>
            <td>
                2013-06-19                        13:09:13                    </td>
            <td>
                Lima -
                Cusco                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10212" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10213</td>
            <td><span class="label label-warning">pendiente</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-important">pen</span>
                120.00                                            </td>
            <td>
                PEN                        120.00                    </td>
            <td>
                2013-06-19                        13:11:07                    </td>
            <td>
                Lima -
                Cusco                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10213" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10214</td>
            <td><span class="label label-important">fallo-pago</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-info">usd</span>
                26.80                                                    (2.619)
            </td>
            <td>
                PEN                        70.00                    </td>
            <td>
                2013-06-19                        13:13:26                    </td>
            <td>
                Lima -
                Arequipa                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10214" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10215</td>
            <td><span class="label label-warning">pendiente</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-info">usd</span>
                30.60                                                    (2.617)
            </td>
            <td>
                PEN                        80.00                    </td>
            <td>
                2013-06-19                        17:13:38                    </td>
            <td>
                Lima -
                Cusco                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10215" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10217</td>
            <td><span class="label label-important">fallo-pago</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-info">usd</span>
                68.90                                                    (2.617)
            </td>
            <td>
                PEN                        180.00                    </td>
            <td>
                2013-06-19                        18:12:53                    </td>
            <td>
                Lima -
                Arequipa                    </td>
            <td>
                2 Passengers 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10217" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10218</td>
            <td><span class="label label-warning">pendiente</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-important">pen</span>
                110.00                                            </td>
            <td>
                PEN                        110.00                    </td>
            <td>
                2013-06-19                        19:10:58                    </td>
            <td>
                Cajamarca -
                Lima                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10218" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10219</td>
            <td><span class="label label-warning">pendiente</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-important">pen</span>
                110.00                                            </td>
            <td>
                PEN                        110.00                    </td>
            <td>
                2013-06-19                        19:17:16                    </td>
            <td>
                Cajamarca -
                Lima                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10219" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10220</td>
            <td><span class="label label-warning">pendiente</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-important">pen</span>
                50.00                                            </td>
            <td>
                PEN                        50.00                    </td>
            <td>
                2013-06-19                        22:18:14                    </td>
            <td>
                Chiclayo -
                Lima                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10220" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10221</td>
            <td><span class="label label-warning">pendiente</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-important">pen</span>
                110.00                                            </td>
            <td>
                PEN                        110.00                    </td>
            <td>
                2013-06-20                        09:59:35                    </td>
            <td>
                Lima -
                Tacna                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10221" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10222</td>
            <td><span class="label label-important">fallo-pago</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-important">pen</span>
                70.00                                            </td>
            <td>
                PEN                        70.00                    </td>
            <td>
                2013-06-20                        12:15:57                    </td>
            <td>
                Lima -
                Arequipa                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10222" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10223</td>
            <td><span class="label label-important">fallo-pago</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-info">usd</span>
                26.50                                                    (2.648)
            </td>
            <td>
                PEN                        70.00                    </td>
            <td>
                2013-06-20                        12:15:58                    </td>
            <td>
                Lima -
                Arequipa                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10223" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10224</td>
            <td><span class="label label-warning">pendiente</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-info">usd</span>
                34.00                                                    (2.648)
            </td>
            <td>
                PEN                        90.00                    </td>
            <td>
                2013-06-20                        12:18:05                    </td>
            <td>
                Lima -
                Trujillo                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10224" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10225</td>
            <td><span class="label label-warning">pendiente</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-important">pen</span>
                70.00                                            </td>
            <td>
                PEN                        70.00                    </td>
            <td>
                2013-06-20                        12:18:15                    </td>
            <td>
                Lima -
                Arequipa                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10225" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10226</td>
            <td><span class="label label-warning">pendiente</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-important">pen</span>
                70.00                                            </td>
            <td>
                PEN                        70.00                    </td>
            <td>
                2013-06-20                        12:19:40                    </td>
            <td>
                Lima -
                Arequipa                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10226" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10227</td>
            <td><span class="label label-warning">pendiente</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-important">pen</span>
                80.00                                            </td>
            <td>
                PEN                        80.00                    </td>
            <td>
                2013-06-20                        15:56:16                    </td>
            <td>
                Lima -
                Ayacucho                    </td>
            <td>
                1 Passenger 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10227" data-original-title="" title=""></i>

            </td>
        </tr>
        <tr>
            <td>10228</td>
            <td><span class="label label-success">pagado</span></td>
            <td>Civa</td>
            <td>
                [alignet]
                <span class="badge badge-important">pen</span>
                200.00                                            </td>
            <td>
                PEN                        200.00                    </td>
            <td>
                2013-06-20                        19:36:53                    </td>
            <td>
                Lima -
                Cajamarca                    </td>
            <td>
                2 Passengers 
                <i class="icon-info-sign pop-venta-detalle pull-right" id="pop-venta-detalle-10228" data-original-title="" title=""></i>

            </td>
        </tr>
    </tbody>
</table>