<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">

        <?= $this->headTitle() ?>

        <?= $this->headMeta() ?>

        <?= $this->headLink() ?>

        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="../assets/ico/favicon.png">
    </head>
    <body>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-45533425-1', 'live-game.org');
      ga('send', 'pageview');
    </script>
        <?= $this->render('_navbar.phtml') ?>
        <div class="container">
            <?= $this->layout()->content ?>
            <?= $this->render('_footer.phtml') ?>
        </div>
        <?= $this->headScript() ?>
    </body>
</html>
