<div class="row-fluid">
    <div class="span10">
        <h3>Events List</h3>
    </div>
    <div class="span2">
        <a class="btn btn-primary pull-right" href='<?= $this->url(array('module' => 'admin', 'controller' => 'event', 'action' => 'new'), 'default', true) ?>'>New</a>
    </div>
</div>

<table id="tbl-reporte-ventas" class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>Id</th>
            <th>Sport</th>
            <th>League</th>
            <th>Name</th>
            <th>Date And Time</th>
            <th>Operations</th>
        </tr>
    </thead>
    <tbody>
        <? foreach ($this->events as $item): $item = (array) $item; ?>
            <tr>
                <td><?= $item['ide'] ?></td>
                <td><?= $item['sport'] ?></td>
                <td><?= $item['league'] ?></td>
                <td><?= $item['event'] ?></td>
                <td><?= $item['dt'] ?></td>
                <td>
                    <? $base = array('module'=>'admin','controller'=>'event','id'=>$item['ide']); ?>
                    <? $url = $this->url($base+array('action'=>'view')); ?>
                    <a class="btn btn-primary" href="<?=$url?>">View</a>
                </td>
            </tr>
        <? endforeach; ?>
    </tbody>
</table>